# Generated by Django 6.0.2 on 2026-04-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleTitle', models.CharField(max_length=100)),
                ('moduleDescription', models.TextField()),
                ('moduleCoach', models.CharField(max_length=100)),
                ('moduleDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsTrainingApp.session')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsTrainingApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsTrainingApp.trainingmodule'),
        ),
        migrations.CreateModel(
            name='EnrolmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Enrolled', max_length=50)),
                ('progress', models.CharField(default='0%', max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsTrainingApp.student')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsTrainingApp.trainingmodule')),
            ],
        ),
    ]
