# Generated by Django 6.0.2 on 2026-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('moduleTitle', models.CharField(max_length=100)),
                ('moduleDescription', models.CharField(max_length=100)),
                ('moduleStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
